[package]
name = "rui"
version = "0.1.0"
authors = ["Onyx Azryn <brycekabat@onyxazryn.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
druid = "0.7.0"
rug = "1.11.0"